Settings:
  ColorSettings:
    Rules:
      - ForegroundColor: Red
        RegexString: \tERR\t
      - ForegroundColor: Red
        RegexString: \Werror\W
      - ForegroundColor: DarkRed
        RegexString: \tIMP\t
      - ForegroundColor: Chocolate
        RegexString: \tWRN\t
      - ForegroundColor: Gray
        RegexString: \tDBG\t
  LogFormats:
#KL logs
    - Regex: ^(?'Time'\d{2}\:\d{2}\:\d{2}\.\d{3})\t(?'Thread'0x[0-9a-fA-F]+)\t(?'Severity'\w+)\t(?'Component'[\w\.]+)?\t?(?'Message'.*)
      FieldsOrder:
        - Time
        - Thread
        - Severity
        - Component
        - Message
      IndexedFields:
        - Thread
        - Severity
        - Component
#LogGrok logs
# 00:07:08.703	10144	0x1	INF	DocumentContainer	Start loading C:\Traces\producttraces (65)\KAV.21.3.7.290_01.26_15.43_4824.SRV.log
    - Regex: ^(?'Time'\d{2}\:\d{2}\:\d{2}\.\d{3})\t(?'Process'\d+)\t(?'Thread'0x[0-9a-fA-F]+)\t(?'Severity'\w+)\t(?'Component'[\w\.]+)?\t?(?'Message'.*)
      FieldsOrder:
        - Time
        - Process
        - Thread
        - Severity
        - Component
        - Message
      IndexedFields:
        - Process
        - Thread
        - Severity
        - Component
